[package]
name = "patentseq"
version = "0.1.0"
authors = ["Erin Moon <erin@hecke.rs>"]
edition = "2018"

[dependencies]
biotypes = {path = "./biotypes"}
chrono = "0.4.11"

[workspace]
members = ["biotypes"]
